services:
  db:
    image: postgres:16.8
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  web:
    image: ${WEB_IMAGE:-ghcr.io/codestorm1/tbtips:latest}
    command: >
      bash -c "bin/migrate && bin/server"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      PHX_SERVER: true
      DATABASE_URL: ecto://postgres:postgres@db:5432/postgres
      SECRET_KEY_BASE: jgsNhkSB9xtSG2fWxW9/gzYWhq+NkdleihelgBX1OKsE6GdSwqH4R1LVCDvpmXej
      PHX_HOST: localhost
      RELEASE_DISTRIBUTION: none
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
